service: webscraper
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  stage: dev
  layers:
    - arn:aws:lambda:us-east-1:585135459468:layer:chrome-aws-lambda:1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:us-east-1:*:table/rates'

functions:
  scraper:
    handler: src/handler.scraper
    timeout: 60
    environment:
      ${file(env.yml):}

resources:
  Resources:
    webscraper:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
